# Generated by Django 5.1.1 on 2024-09-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_menu_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
